PMS/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace PMS.Web.UI.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PMS/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PMS.Web.UI.Core.Interfaces;
using PMS.Web.UI.Core.Models;
using PMS.Web.UI.ViewModels;

namespace PMS.Web.UI.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {

        #region Data Members
        private readonly IEmployeeRepository _employeeRepository;
        private readonly UserManager<IdentityUser> _userManager;
        public EmployeeController(IEmployeeRepository employeeRepository, UserManager<IdentityUser> userManager)
        {
            _employeeRepository = employeeRepository;
            _userManager = userManager;
        }

        #endregion

        #region ActionResults

        public IActionResult Index()
        {
            return View();
        }

        #endregion

        #region Datatable

        /// <summary>
        /// Patient datatable
        /// </summary>
        /// <returns></returns>
        public JsonResult EmployeeDataTable(JqueryDataTableViewModel param)
        {
            try
            {
                var sortDirection = Request.Query["sSortDir_0"];//asc or desc
                var sortColumnIndex = Convert.ToInt32(Request.Query["iSortCol_0"]);//Get Sorting Index of Column 
                IEnumerable<Employee> qry;

                // incase no app cat is not there we will saw them todays 
                qry = _employeeRepository.GetAllReadonly;
                //Get total count
                var totalrecords = qry.Count();

                if (!string.IsNullOrEmpty(param.sSearch))
                {
                    qry = qry.Where(c => c.FirstName != null && c.FirstName.ToLower().Contains(param.sSearch.ToLower())
                                         || c.LastName != null &&
                                         c.LastName.Contains(param.sSearch.ToLower())
                                         || c.Number != null &&
                                         c.Number.Contains(param.sSearch.ToLower())
                                         || c.Grade != null &&
                                         c.Grade.Contains(param.sSearch.ToLower())
                                         || c.Department != null &&
                                         c.Department.Contains(param.sSearch.ToLower())
                                         );
                }
                if (sortColumnIndex == 1)//fname
                {
                    if (sortDirection == "desc")
                    {
                        //Run if sort direction is Descending
                        qry = qry.OrderByDescending(a => a.FirstName);
                    }
                    else if (sortDirection == "asc")
                    {
                        //Run if sort direction is Ascending
                        qry = qry.OrderBy(a => a.FirstName);
                    }
                }
                if (sortColumnIndex == 2)//email
                {
                    if (sortDirection == "desc")
                    {
                        //Run if sort direction is Descending
                        qry = qry.OrderByDescending(a => a.LastName);
                    }
                    else if (sortDirection == "asc")
                    {
                        //Run if sort direction is Ascending
                        qry = qry.OrderBy(a => a.LastName);
                    }
                }

                //Pagination
                if (param.iDisplayLength != -1)
                    qry = qry.Skip(param.iDisplayStart).Take(param.iDisplayLength);

                var result = from c in qry.ToList()
                             select new[]
                             {
                             c.EmployeeId.ToString(),
                             c.FirstName + " " + c.LastName,
                             c.Number,
                             c.Grade,
                             c.AppraisalPeriod,
                             c.Department
                         };

                return Json(new
                {
                    aaData = result,
                    param.sEcho,
                    iTotalRecords = totalrecords,
                    iTotalDisplayRecords = totalrecords,
                });

            }
            catch (Exception ex)
            {
                //Rollbar.RollbarLocator.RollbarInstance.Error(ex.Message);
                return Json(new { Response = ex.InnerException.Message });
            }
        }

        #endregion
    }
}

PMS/Controllers/GoalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PMS.Web.UI.Core.Interfaces;
using PMS.Web.UI.Core.Models;
using PMS.Web.UI.ViewModels;

namespace PMS.Web.UI.Controllers
{
    [Authorize]
    public class GoalController : Controller
    {
        #region Data Members
        private readonly IGoalRepository _goalRepository;
        private readonly UserManager<IdentityUser> _userManager;
        public GoalController(IGoalRepository goalRepository, UserManager<IdentityUser> userManager)
        {
            _goalRepository = goalRepository;
            _userManager = userManager;
        }

        #endregion

        #region ActionResults

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Add New goal
        /// </summary>
        /// <returns></returns>
        public IActionResult Add()
        {
            return View("~/Views/Shared/_AddEditGoal.cshtml");
        }

        /// <summary>
        /// Edit goal
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult Edit(int id)
        {
            var patient = _goalRepository.GetById(id);
            var model = Mapper.Map<Goal, GoalViewModel>(patient);
            return View("~/Views/Shared/_AddEditGoal.cshtml", model);
        }

        /// <summary>
        /// Update Record
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> AddEdit(GoalViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var user = _userManager.GetUserId(HttpContext.User);
                if (vm.GoalId > 0)
                {
                    var goal = _goalRepository.GetById(vm.GoalId);
                    if (goal == null) return RedirectToAction("Index");
                    vm.ModifiedBy = user;
                    vm.CreatedBy = goal.CreatedBy;
                    vm.DateCreated = goal.DateCreated;
                    goal = Mapper.Map<GoalViewModel, Goal>(vm);
                    await _goalRepository.UpdateAsync(goal);
                }
                else
                {
                    vm.CreatedBy = user;
                    vm.ModifiedBy = user;
                    var goal = Mapper.Map<GoalViewModel, Goal>(vm);
                    await _goalRepository.CreateAsync(goal);
                }
                return RedirectToAction("Index");
            }
            return View("~/Views/Shared/_AddEditGoal.cshtml", vm);
        }

        #endregion

        #region Datatable

        /// <summary>
        /// Patient datatable
        /// </summary>
        /// <returns></returns>
        public JsonResult GoalDataTable(JqueryDataTableViewModel param)
        {
            try
            {
                var sortDirection = Request.Query["sSortDir_0"];//asc or desc
                var sortColumnIndex = Convert.ToInt32(Request.Query["iSortCol_0"]);//Get Sorting Index of Column 
                IEnumerable<Goal> qry;

                // incase no app cat is not there we will saw them todays 
                qry = _goalRepository.GetAllReadonly;
                //Get total count
                var totalrecords = qry.Count();

                if (!string.IsNullOrEmpty(param.sSearch))
                {
                    qry = qry.Where(c => c.Name != null && c.Name.ToLower().Contains(param.sSearch.ToLower())
                                         || c.MeasureOfPerformance != null &&
                                         c.MeasureOfPerformance.Contains(param.sSearch.ToLower())
                                         || c.Weightage.ToString().Contains(param.sSearch.ToLower())
                                         || c.Level1 != null &&
                                         c.Level1.Contains(param.sSearch.ToLower())
                                         || c.Level2 != null &&
                                         c.Level2.Contains(param.sSearch.ToLower())
                                         || c.Level2 != null &&
                                         c.Level2.Contains(param.sSearch.ToLower())
                                         || c.Level3 != null &&
                                         c.Level3.Contains(param.sSearch.ToLower())
                                         || c.Level4 != null &&
                                         c.Level4.Contains(param.sSearch.ToLower())
                                         || c.Level5 != null &&
                                         c.Level5.Contains(param.sSearch.ToLower())
                                         || c.Guideline != null &&
                                         c.Guideline.Contains(param.sSearch.ToLower())
                                         );
                }
                if (sortColumnIndex == 1)//fname
                {
                    if (sortDirection == "desc")
                    {
                        //Run if sort direction is Descending
                        qry = qry.OrderByDescending(a => a.Name);
                    }
                    else if (sortDirection == "asc")
                    {
                        //Run if sort direction is Ascending
                        qry = qry.OrderBy(a => a.Name);
                    }
                }
                if (sortColumnIndex == 2)//email
                {
                    if (sortDirection == "desc")
                    {
                        //Run if sort direction is Descending
                        qry = qry.OrderByDescending(a => a.MeasureOfPerformance);
                    }
                    else if (sortDirection == "asc")
                    {
                        //Run if sort direction is Ascending
                        qry = qry.OrderBy(a => a.MeasureOfPerformance);
                    }
                }


                //Pagination
                if (param.iDisplayLength != -1)
                    qry = qry.Skip(param.iDisplayStart).Take(param.iDisplayLength);

                var result = from c in qry.ToList()
                             select new[]
                             {
                             c.GoalId.ToString(),
                             c.Name,
                             c.MeasureOfPerformance,
                             c.Weightage.ToString(),
                             c.Level5,
                             c.Level3,
                             c.Guideline
                         };

                return Json(new
                {
                    aaData = result,
                    param.sEcho,
                    iTotalRecords = totalrecords,
                    iTotalDisplayRecords = totalrecords,
                });

            }
            catch (Exception ex)
            {
                //Rollbar.RollbarLocator.RollbarInstance.Error(ex.Message);
                return Json(new { Response = ex.InnerException.Message });
            }
        }

        #endregion
    }
}

PMS/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SigInManager;
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Performance Management System</title>
    <link rel="apple-touch-icon" href="~/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/images/ico/favicon.ico">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Quicksand:300,400,500,700" rel="stylesheet">
    <link href="//maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css" rel="stylesheet">
    @*<link rel="stylesheet" type="text/css" href="~/css/vendors.css">
    <!-- END VENDOR CSS-->
    <!-- BEGIN MODERN CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/app.css">
    <!-- END MODERN CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/core/menu/menu-types/vertical-menu-modern.css">
    <link rel="stylesheet" type="text/css" href="~/css/core/colors/palette-gradient.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/css/charts/jquery-jvectormap-2.0.3.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/css/charts/morris.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/simple-line-icons/style.css">
    <link rel="stylesheet" type="text/css" href="~/css/core/colors/palette-gradient.css">
    <!-- END Page Level CSS-->
    <link rel="stylesheet" href="~/css/site.css" />*@
    
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/vendors.css">
    <!-- END VENDOR CSS-->
    <!-- BEGIN MODERN CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/app.css">
    <!-- END MODERN CSS-->
    <environment include="Development">
        <!-- BEGIN Page Level CSS-->
        <link rel="stylesheet" type="text/css" href="~/css/core/menu/menu-types/vertical-menu-modern.css">
        <link rel="stylesheet" type="text/css" href="~/css/core/colors/palette-gradient.css">
        <link rel="stylesheet" type="text/css" href="~/vendors/css/charts/jquery-jvectormap-2.0.3.css">
        <link rel="stylesheet" type="text/css" href="~/vendors/css/charts/morris.css">
        <link rel="stylesheet" type="text/css" href="~/fonts/simple-line-icons/style.css">
        <link rel="stylesheet" type="text/css" href="~/css/core/colors/palette-gradient.css">
        <!-- END Page Level CSS-->
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", false)
</head>
<body class="vertical-layout vertical-menu-modern 2-columns   menu-expanded fixed-navbar" data-open="click" data-menu="vertical-menu-modern" data-col="2-columns">

    <!-- fixed-top-->
    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-dark navbar-shadow">
        <div class="navbar-wrapper">
            <div class="navbar-header">
                <ul class="nav navbar-nav flex-row">
                    <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                    <li class="nav-item mr-auto">
                        <a class="navbar-brand" asp-action="Index" asp-controller="Dashboard">
                            @*<img class="brand-logo" alt="modern admin logo" src="/img/Pure-Smile-logo.png">*@
                            <h3 class="brand-text">PMS</h3>
                        </a>
                    </li>
                    <li class="nav-item d-none d-md-block float-right"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i class="toggle-icon ft-toggle-right font-medium-3 white" data-ticon="ft-toggle-right"></i></a></li>
                    <li class="nav-item d-md-none">
                        <a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="la la-ellipsis-v"></i></a>
                    </li>
                </ul>
            </div>
            <div class="navbar-container content">
                <div class="collapse navbar-collapse" id="navbar-mobile">
                    <ul class="nav navbar-nav mr-auto float-left">
                        <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>
                        <li class="nav-item nav-search">
                            <a class="nav-link nav-link-search" href="#"><i class="ficon ft-search"></i></a>
                            <div class="search-input">
                                <input class="input" type="text" placeholder="Explore Modern...">
                            </div>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav float-right">
                        <li class="dropdown dropdown-user nav-item">
                            <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                                <span class="mr-1">
                                    Hello,
                                    <span class="user-name text-bold-700">@User.Identity.Name</span>
                                </span>
                                <span class="avatar avatar-online">
                                    <img src="/images/portrait/small/avatar-s-19.png" alt="avatar"><i></i>
                                </span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#"><i class="ft-user"></i> Edit Profile</a>
                                <div class="dropdown-divider"></div>
                                <form asp-controller="Account" asp-action="Logout" id="logoutForm1" method="post">
                                    <a class="dropdown-item" href="javascript:document.getElementById('logoutForm1').submit()"><i class="ft-power"></i> Logout</a>
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow" data-scroll-to-active="true">
        <div class="main-menu-content">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                <li class="navigation-header">
                    @if (User.IsInRole("Admin"))
                    {
                        <span data-i18n="nav.category.layouts">Admin</span><i class="la la-ellipsis-h ft-minus" data-toggle="tooltip" data-placement="right" data-original-title="Layouts"></i>
                    }
                    else
                    {

                        <span data-i18n="nav.category.layouts">User</span><i class="la la-ellipsis-h ft-minus" data-toggle="tooltip" data-placement="right" data-original-title="Layouts"></i>
                    }
                </li>
                <li class=" nav-item">
                    <a href="#"><i class="la la-home"></i><span class="menu-title" data-i18n="nav.dash.main">Dashboard</span><span class="badge badge badge-info badge-pill float-right mr-2">3</span></a>
                    <ul class="menu-content">
                        <li>
                            <a asp-controller="Dashboard" asp-action="Index" class="menu-item">
                                My Dashboard
                            </a>
                        </li>
                    </ul>
                </li>
                <li class=""><a asp-controller="Employee" asp-action="Index"><i class="la la-user"></i><span class="menu-title" data-i18n="">Employees</span></a></li>
                <li class=""><a asp-controller="Goal" asp-action="Index"><i class="la la-pie-chart"></i><span class="menu-title" data-i18n="">Goals</span></a></li>
            </ul>
        </div>
    </div>
    <!-------- Body -----=-->
    <div class="app-content content">
        <div class="content-wrapper">
            @RenderBody()
        </div>
    </div>
    <!-- ////////////////////////////////////////////////////////////////////////////-->

    <footer class="footer footer-static footer-light navbar-border navbar-shadow">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
            <span class="float-md-left d-block d-md-inline-block">
                Copyright &copy; @DateTime.Now.Year <a class="text-bold-800 grey darken-2" href="http://lpinfotech.com/"
                                                       target="_blank">LP InfoTech</a>, All rights reserved.
            </span>
            <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Pure Smiles <i class="ft-heart pink"></i></span>
        </p>
    </footer>
    @*<!-- BEGIN VENDOR JS-->
    <script src="~/vendors/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN MODERN JS-->
    <script src="~/js/core/app-menu.js" type="text/javascript"></script>
    <script src="~/js/core/app.js" type="text/javascript"></script>
    <script src="~/js/scripts/customizer.js" type="text/javascript"></script>
    <!-- END MODERN JS-->*@

    <environment include="Development">
        <!-- BEGIN VENDOR JS-->
        <script src="~/vendors/js/vendors.min.js" type="text/javascript"></script>
        <!-- BEGIN VENDOR JS-->
        <!-- BEGIN MODERN JS-->
        <script src="~/js/core/app-menu.js" type="text/javascript"></script>
        <script src="~/js/core/app.js" type="text/javascript"></script>
        <script src="~/js/scripts/customizer.js" type="text/javascript"></script>
        <!-- END MODERN JS-->
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

PMS/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - PMS</title>
    @*<link rel="icon" type="image/png" href="favicon -P.ico">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">*@

    <link rel="apple-touch-icon" href="~/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/images/ico/favicon.ico">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Quicksand:300,400,500,700" rel="stylesheet">
    <link href="//maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css" rel="stylesheet">
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/vendors.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/css/forms/icheck/icheck.css">
    <link rel="stylesheet" type="text/css" href="~/vendors/css/forms/icheck/custom.css">
    <!-- END VENDOR CSS-->
    <!-- BEGIN MODERN CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/app.css">
    <!-- END MODERN CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="~/css/core/menu/menu-types/vertical-menu-modern.css">
    <link rel="stylesheet" type="text/css" href="~/css/core/colors/palette-gradient.css">
    <link rel="stylesheet" type="text/css" href="~/css/pages/login-register.css">
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    <link href="~/css/Site.css" rel="stylesheet" />
    <!-- END Custom CSS-->


</head>
<body class="vertical-layout vertical-menu-modern 1-column  bg-full-screen-image menu-expanded blank-page blank-page"
      data-open="click" data-menu="vertical-menu-modern" data-col="1-column">
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                <section class="flexbox-container">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="col-md-4 col-10 box-shadow-2 p-0">
                            <div class="card border-grey border-lighten-3 px-1 py-1 m-0">
                                <div class="card-header border-0">
                                    <div class="card-title text-center">
                                        @*<img src="~/img/Pure-Smile-logo.png" alt="branding logo">*@
                                        Performance Management System
                                    </div>
                                    <h6 class="card-subtitle line-on-side text-muted text-center font-small-3 pt-2">
                                        <span>Easily Using</span>
                                    </h6>
                                </div>
                                <div class="card-content">
                                    <div class="card-body">
                                        @RenderBody()
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- ////////////////////////////////////////////////////////////////////////////-->
    <footer class="footer footer-static footer-light navbar-border navbar-shadow">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2">
            <span class="float-md-left d-block d-md-inline-block">
                Copyright &copy; @DateTime.Now.Year <a class="text-bold-800 grey darken-2" href="http://serenetechnologies.ca/"
                                                       target="_blank">SereneTechnologies</a>, All rights reserved.
            </span>
            <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Pure Smiles <i class="ft-heart pink"></i></span>
        </p>
    </footer>

    <!-- BEGIN VENDOR JS-->
    <script src="~/vendors/js/vendors.min.js" type="text/javascript"></script>
    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script src="~/vendors/js/forms/validation/jqBootstrapValidation.js"
            type="text/javascript"></script>
    <script src="~/vendors/js/forms/icheck/icheck.min.js" type="text/javascript"></script>
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN MODERN JS-->
    <script src="~/js/core/app-menu.js" type="text/javascript"></script>
    <script src="~/js/core/app.js" type="text/javascript"></script>
    <!-- END MODERN JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    <script src="~/js/scripts/forms/form-login-register.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL JS-->

    @RenderSection("scripts", required: false)
</body>
</html>